baseURL: "https://bouroo.github.io"
languageCode: "en-us"
title: "Kawin's Page"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Kawin's Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Kawin's Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Kawin."
    subtitle: "I build things for the backend"
    content: "A passionate backend developer. I tend to make use of modern backend technologies to build services that looks great, feels fantastic, and functions correctly."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "https://www.linkedin.com/in/kawin-viriyaprasopsook-5b0aa428/"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/bouroo
        - icon: fab fa-twitter
          url: https://twitter.com/bouroo
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a software developer with a passion for backend development. I have a background in computer engineering, and I have a strong interest in the intersection of technology and art. I am currently working as a backend developer at [Zercle Technology Co., Ltd.](https://zercle.tech) in Khon Kaen, TH. 

      I am currently working on a project that will be used to help people be better in the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Go"
        - "Linux"
        - "Docker"
        - "Proxmox VE"
        - "MariaDB"
        - "Traefik"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Senior System Engineer"
        company: "COOPNIX Co., Ltd. · Full-time"
        companyUrl: "https://coopnix.co.th"
        date: "2016 - Present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://coopnix.co.th"
        content: |
          - Maintain customer's servers & VMs.
          - Improve overall system performance & security.

      - job: "Chief Technology Officer"
        company: "Zercle Tecnology · Self-employed"
        companyUrl: "https://zercle.tech"
        date: "2012 - Present"
        featuredLink:
          enable: true
          url: "https://zercle.tech"
        info:
          enable: false
        content: |
          - Design and provide system architecture/infrastructure.
          - Review & Improve back-end project's code.

      - job: "Computer Engineer"
        company: "Provincial Waterworks Authority · Full-time"
        companyUrl: "https://pwa.co.th"
        date: "Jan 2014 - Jul 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://pwa.co.th"
        content: |
          - Maintain & Improve networking stability, performance, security.
          - Maintain & Provide Servers, VMs.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Engineering (B.Eng.)"
        school:
          name: "Khon Kaen University, Thailand"
          url: "https://kku.ac.th"
        date: "2008 - 2012"
        GPA: "2.83 out of 4.0"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "Khon Kaen University"
          url: "https://kku.ac.th"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: KKU DMS
        content: KhonKaen University's Document Mamange System.
        image: /images/projects/profile.png
        featured:
          name: Project
          link: https://dms.kku.ac.th/
        badges:
          - "PHP"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

      - title: KKU Payment Hub
        content: KhonKaen University's Digital payment hub.
        image: /images/projects/converter.jpg
        featured:
          name: Project
          link: https://payment-web.kku.ac.th/
        badges:
          - "Go"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

      - title: COVID-19 vaccine reservation
        content: Khon Kaen's COVID-19 vaccine reservation.
        image: /images/projects/profile2.jpg
        featured:
          name: Project
          link: https://vaccine.kku.ac.th
        badges:
          - "Go"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

      - title: KKU Software License Reservation
        content: Khon Kaen University's Software license reservation.
        image: /images/projects/profile2.jpg
        featured:
          name: Project
          link: https://app-reserve.kku.ac.th
        badges:
          - "Go"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

      - title: KMUTT Payment Hub
        content: King Mongkut's University of Technology Thonburi's Digital payment hub.
        image: /images/projects/profile2.jpg
        featured:
          name: Project
          link: https://paymenthub.kmutt.ac.th/
        badges:
          - "Go"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

      - title: KMUTT Software License Reservation
        content: King Mongkut's University of Technology Thonburi's App license reservation.
        image: /images/projects/profile2.jpg
        featured:
          name: Project
          link: https://license.kmutt.ac.th
        badges:
          - "Go"
          - "MariaDB"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/zercle

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: bouroo@gmail.com
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/bouroo
      linkedin: https://www.linkedin.com/in/kawin-viriyaprasopsook-5b0aa428/
      twitter: https://twitter.com/bouroo
      instagram: https://instagram.com/bouroo
      facebook: https://facebook.com/k.bouroo

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false